# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - amalnamah-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
        with:
          nuget-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild amalnamah-api.csproj /nologo /verbosity:detailed /t:Build /p:OutDir=".\publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: 'D:\a\amalnamah-api\amalnamah-api\publish'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.7
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C39F32BC643A44F5973F9DC75B67010C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1979A45CF75D4AE6B0A67E08B74B0564 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA7453785B9F4B3AA7259111C59F9F95 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'amalnamah-api'
          slot-name: 'Production'
          package: .
          
